// Builds src/ui/assets/generated.ts from ui-assets/, the site's favicon and the two font
// packages. scripts/gen-ui-assets.ts writes it; test/ui/assets.test.ts regenerates it in memory
// and fails while the committed file is stale.
//
// The assets are TypeScript string constants, not files read at runtime, so the same module
// works in the tsc ESM build, the babel CJS build, the esbuild CLI bundle, vitest and Bun.
import * as esbuild from "esbuild"
import { createHash } from "node:crypto"
import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"

export const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
export const generatedPath = path.join(rootDir, "src", "ui", "assets", "generated.ts")

interface Asset {
  // The exported constant's name
  readonly id: string
  // The source's name; the served name inserts the hash before the extension
  readonly file: string
  readonly contentType: string
  readonly encoding: "utf8" | "base64"
  readonly body: string
  readonly hash: string
}

const LIGHT_BLOCK = /:root\[data-theme="light"\]\s*\{([^}]*)\}/g

const hashOf = (bytes: string | Buffer): string => createHash("sha256").update(bytes).digest("hex").slice(0, 10)

export const hashedName = (file: string, hash: string): string => {
  const dot = file.lastIndexOf(".")
  return `${file.slice(0, dot)}.${hash}${file.slice(dot)}`
}

const read = (...segments: Array<string>): Buffer => fs.readFileSync(path.join(rootDir, ...segments))

const textAsset = (id: string, file: string, contentType: string, body: string): Asset => ({
  id,
  file,
  contentType,
  encoding: "utf8",
  body,
  hash: hashOf(body)
})

const fontAsset = (id: string, pkg: string, file: string): Asset => {
  const bytes = read("node_modules", "@fontsource-variable", pkg, "files", file)
  return {
    id,
    file,
    contentType: "font/woff2",
    encoding: "base64",
    body: bytes.toString("base64"),
    hash: hashOf(bytes)
  }
}

// With no data-theme the UI follows the system: the light set again, under the media query
export const withSystemLight = (tokens: string): string => {
  const blocks = Array.from(tokens.matchAll(LIGHT_BLOCK))
  if (blocks.length !== 1) {
    throw new Error(`tokens.css: expected one :root[data-theme="light"] block, found ${blocks.length}`)
  }
  return `${tokens}\n@media (prefers-color-scheme: light) {\n  :root:not([data-theme]) {${blocks[0][1]}}\n}\n`
}

const minifyCss = async (css: string): Promise<string> =>
  (await esbuild.transform(css, { loader: "css", minify: true, legalComments: "none" })).code

const bundleScript = async (entry: string): Promise<string> => {
  const result = await esbuild.build({
    entryPoints: [path.join(rootDir, "ui-assets", entry)],
    tsconfig: path.join(rootDir, "tsconfig.ui-assets.json"),
    bundle: true,
    write: false,
    minify: true,
    format: "iife",
    platform: "browser",
    target: "es2020",
    legalComments: "none",
    logLevel: "silent"
  })
  return result.outputFiles[0].text
}

const render = (assets: ReadonlyArray<Asset>): string => {
  const constants = assets.map((asset) =>
    [
      `export const ${asset.id}: UiAsset = {`,
      `  name: ${JSON.stringify(hashedName(asset.file, asset.hash))},`,
      `  contentType: ${JSON.stringify(asset.contentType)},`,
      `  encoding: ${JSON.stringify(asset.encoding)},`,
      `  hash: ${JSON.stringify(asset.hash)},`,
      `  body: ${JSON.stringify(asset.body)}`,
      `}`
    ].join("\n")
  )
  return [
    `// Generated by scripts/gen-ui-assets.ts from ui-assets/, site/public/favicon.svg and the`,
    `// @fontsource-variable packages. Do not edit: run \`bun gen-ui-assets\` (the build runs it too).`,
    ``,
    `export interface UiAsset {`,
    `  // The served file name, with the content hash: ui.<hash>.css`,
    `  readonly name: string`,
    `  readonly contentType: string`,
    `  readonly encoding: "utf8" | "base64"`,
    `  readonly hash: string`,
    `  readonly body: string`,
    `}`,
    ``,
    constants.join("\n\n"),
    ``,
    `export const assets: ReadonlyArray<UiAsset> = [${assets.map((asset) => asset.id).join(", ")}]`,
    ``
  ].join("\n")
}

// The source of src/ui/assets/generated.ts
export const generate = async (): Promise<string> => {
  const fonts = [
    fontAsset("martianMonoFont", "martian-mono", "martian-mono-latin-standard-normal.woff2"),
    fontAsset("geistFont", "geist", "geist-latin-wght-normal.woff2")
  ]

  // fonts.css names each font by its source file; point it at the hashed one
  let fontsCss = read("ui-assets", "fonts.css").toString("utf8")
  for (const font of fonts) {
    const ref = `url(./${font.file})`
    if (!fontsCss.includes(ref)) throw new Error(`fonts.css does not reference ${font.file}`)
    fontsCss = fontsCss.replaceAll(ref, `url(./${hashedName(font.file, font.hash)})`)
  }
  const tokens = withSystemLight(read("ui-assets", "tokens.css").toString("utf8"))
  const css = await minifyCss([fontsCss, tokens, read("ui-assets", "ui.css").toString("utf8")].join("\n"))

  return render([
    textAsset("uiCss", "ui.css", "text/css; charset=utf-8", css),
    textAsset("uiJs", "ui.js", "text/javascript; charset=utf-8", await bundleScript("ui.ts")),
    // The stubs page's editor, loaded on that page only
    textAsset("editorJs", "editor.js", "text/javascript; charset=utf-8", await bundleScript("editor-main.ts")),
    textAsset("favicon", "favicon.svg", "image/svg+xml", read("site", "public", "favicon.svg").toString("utf8")),
    ...fonts
  ])
}
